### ISSUE TITLE
Ideas for additional persistent storage

### ISSUE THREAD

**Issue by christroutner** [gruns/ImmortalDB#23]
Love the idea behind this project. Some ideas for additional ways to store data and self-heal the data:
- Also fire up a [browser-based IPFS node](https://github.com/ipfs/js-ipfs) and persist the data to the IPFS network.
- Using [BITBOX SDK](https://developer.bitcoin.com/bitbox/docs/getting-started) to write data to the BCH blockchain via the [Memopress protocol](https://developer.bitcoin.com/tutorials/memopress/)

**Comment by gruns** [comment]
Great ideas. Both are possible; ImmortalDB has full support for async data
stores. Like those that use the network, a la IPFS.

Would you use these stores? If so, for which kinds of data?

I wouldn't add them as default stores to ImmortalDB unless widely used, as
they'd likely balloon ImmortalDB's footprint considerably due to their large
dependencies. But they'd be wonderful optional stores, voluntarily used like

```js
import { IpfsStore } from 'immortal-db-ipfs-store'
import { ImmortalStorage, LocalStorageStore } from 'immortal-db'

const stores = [LocalStorageStore, IpfsStore]
const db = ImmortalStorage(stores)
```

To get started, take a look at the existing storage implementations. Like

* https://github.com/gruns/ImmortalDB/blob/master/src/web-storage.js

It's straightforward to implement a new Store. The API is simple:

 * `set(key, value)`
 * `get(key, default=null)`
 * `remove(key)`

That's it.

Are you going to take a stab at these?

**Comment by christroutner** [comment]
Just suggestions. And I agree, these types of stores would not be applicable to normal use case. They would be best for situations where immutable data is the primary feature.

- IPFS is less immutable as you can use IPNS to point to the tip of a DAG. This kind of storage is also computationally cheap and monetarily free.

- Storing to the blockchain would be for true immutibility, with no change of changing the data later. It would also cost a small fraction of cent (in BCH) to publish the data to the blockchain. The storage limitation for an OP_RETURN is 220 bytes, but that could hold a little bit of JSON or a retrieval hash for the IPFS network.

I don't have any plans to add these features. These are really just intended as fun ideas.

However, if anyone is interested in using BCH or BITBOX for immutable stores, you can ask questions in [our dev channel](https://discord.gg/GXur7m9).

**Comment by gruns** [comment]
> I don't have any plans to add these features. These are really just intended
> as fun ideas.

Awesome.

Thank you for opening this Issue, Chris. Don't hesitate to let me know if
there's anything else I can do for you.
